# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Use a package of configuration called an orb.
orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  create_infra: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file infra/template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-2

  configure_infra:
    docker:
      - image: python:3.11.1-alpine3.17
      steps:
        - checkout
        - add_ssh_keys:
            fingerprints: ["c8:fd:ca:a8:3c:99:67:c2:ef:62:24:b4:a9:84:8b:47"]
        - run:
            name: install deps
            command: |
              apk add --update ansible
        - run:
            name: Configure server
            command: |
              ansible-playbook -i inventory main.yml

workflows:
  deploy_workflow:
    jobs:
      # - create_infra
      - configure_infra

